### PR TITLE
Tweak fiber example output

### PR DESCRIPTION
**Pull request by sogaiu**

### CODE REVIEW

**Review by pepe — COMMENTED** [review]
I think it will be better to have `prints` everywhere (even on line 43).

**Comment by pyrmont** [comment]
I had the same reaction as @pepe. Why treat the lines you've edited differently than the ones around them? (There might be a good reason; it's just not clear to me what it is.)

**Comment by uvtc** [comment]
I've never seen a good notation for how to indicate in a comment what the line in question *prints out*. I use `#=>` for "evaluates to":

~~~python
(+ 1 2)  #=> 3
~~~

but often, to indicate "prints out", just leave it as

~~~python
(print (+ 1 2))  # 3
~~~

Maybe the unicode U+1F5B6 symbol for "printer" ...

~~~python
(print (+ 1 2))  #🖶 3
~~~

;)

**Comment by pepe** [comment]
@uvtc that is on point. What about just replicate REPL output? But then we will need to fix all examples :-).

**Comment by sogaiu** [comment]
Just to spell things out:

* the output is inconsistent
* keywords print without colons in janet via `print`

In combination I was confused with the doc as it was.

**Comment by sogaiu** [comment]
Regarding fixing the examples, I could probably convince myself to do it.

**Comment by uvtc** [comment]
> keywords print without colons in janet via `print`

Oh, wow. Why is that? I'd think that's a bug. I searched the issues here but it did not come up.

**Comment by pyrmont** [comment]
@uvtc I think it's because the 'value' of a keyword is the string and `print` prints the value of the symbol as opposed to a textual representation of it (that's why passing a data structure to `print` results in it coming out as a pointer reference).

In the case of keywords, the `:` is syntactic sugar that identifies it as a keyword rather than being part of its value. Functions that print a textual representation (like `pp`) will produce `:keyword`.

**Comment by sogaiu** [comment]
It turns out in Clojure there are at least 2 flavors of printing -- one for humans and one for machines.

I took what pyrmont mentioned above (pp vs print) as an example of that type of thing.  Though in Clojure you get the colon in both cases IIRC.

I imagined it was a conscious decision to not have the colon here, but I don't know the reasons why.  May be even having the colon in output in Clojure's case is arbitrary in some sense.

**Pull request merged**
