### PR TITLE
Mention Sublime Text package for Janet support

### PR DESCRIPTION
**Pull request by archydragon**

### CODE REVIEW

**Comment by sogaiu** [comment]
Looks interesting :)

**Review by pepe — APPROVED** [review]
LGTM

**Comment by sogaiu** [comment]
I tried it on Windows.

I observed the nice syntax highlighting, symbol navigation, file evaluation ("Build"), and the SublimeREPL integration.

These have been working fine for me so far :+1: 

A couple of things that were slightly bumpy were:

* Somehow I didn't see anything relevant in "Package Control" -- it was the first time I'd tried that though, so perhaps it was pilot error (or may be it's related to my use of scoop, see next item)
* I had used scoop to install SublimeText so I guess that's why the "Sublime Text user packages directory" was different from what was listed at the repository [1].

In any case, thanks for your effort :)

---

[1] The directory here was along the lines of: `%USERPROFILE%\scoop\apps\sublime-text\current\Data\packages\User`

**Comment by archydragon** [comment]
> Somehow I didn't see anything relevant in "Package Control"

Yep, I stated it there a bit ahead of time, as my PR to package control channel is still under review: https://github.com/wbond/package_control_channel/pull/8700 . Sorry for that confusion!

As of scoop, I'm afraid, I won't be able to cover all possible ways of installing software on all different OSes, so I only listed the most common ones.

**Pull request merged**
