### PR TITLE
Revert "Add C source links to the website."

### PR DESCRIPTION
**Pull request by bakpakin**
Reverts janet-lang/janet-lang.org#57

### CODE REVIEW

**Comment by bakpakin** [comment]
Did not build and the dependency was not included in the repository. Reverting until fixed.

**Comment by andrewchambers** [comment]
Didn't build?

**Comment by bakpakin** [comment]
Yes there were issues, even after the dependency was installed, where the site didn’t seem to build. More to the point though, I would much prefer a small dependency like that to be bundled into the repository.

**Comment by andrewchambers** [comment]
I see, for this use we essentially only need the 'func-info' function from where-defined anyway. The annoying thing is libbacktrace wasn't bundled for my distro.

**Pull request merged**
